### ISSUE TITLE
List of versions

### ISSUE THREAD

**Issue by palette-knife25** [oswaldoludwig/Adversarial-Learning-for-Generative-Conversational-Agents#6]
Could you please list versions of the packages that you use in this project? I saw in another issue that it requires Python 2, but what about other stuff (e.g., Keras)?

**Comment by oswaldoludwig** [comment]
These codes are from 4 years ago, so they ran on Ubuntu 14.04.3 LTS, Python 2.7.6, Theano 0.9.0 and Keras 2.0.4.

**Comment by palette-knife25** [comment]
Thank you!
